### ISSUE TITLE
Structure tests fails (maven property missing) with Maven 3.0.5

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/openjdk-runtime#145]
During  `mvn clean install` the following error show up
```
status: Image is up to date for gcr.io/gcp-runtimes/structure_test:latest
2017/09/01 15:00:07 Running tests for file /cfg/openjdk8-structure.yaml
--- FAIL: TestAll (0.21s)
    --- FAIL: TestAll/Command_Test:_correct_java_version_is_installed (0.12s)
        structure_test_v1.go:171: Executing: [java -version]
        structure_test_v1.go:188: stderr: openjdk version "1.8.0_131"
                OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
                OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
        structure_test.go:56: Expected string 'openjdk version "1\.${openjdk.version.major}.*${openjdk.version.minor}"' not found in error!
    --- FAIL: TestAll/Command_Test:_correct_javac_version_is_installed (0.09s)
        structure_test_v1.go:171: Executing: [javac -version]
        structure_test_v1.go:188: stderr: javac 1.8.0_131
        structure_test.go:56: Expected string 'javac 1\.${openjdk.version.major}.*${openjdk.version.minor}' not found in error!
        structure_test.go:45: Total tests run: 2

```

The generated `target/test-classes/openjdk8-structure.yaml` have the following content:
``` yaml
schemaVersion: 1.0.0

commandTests:
- name: 'correct java version is installed'
  command: ['java', '-version']
  expectedError: ['openjdk version "1\.${openjdk.version.major}.*${openjdk.version.minor}"']
- name: 'correct javac version is installed'
  command: ['javac', '-version']
  expectedError: ['javac 1\.${openjdk.version.major}.*${openjdk.version.minor}']
```

I think that the maven properties `openjdk.version.major` and `openjdk.version.minor` are not correctly set or interpreted by maven.

The issue is also present for the `openjdk9` project
