### ISSUE TITLE
openjdk11 not working

### ISSUE THREAD

**Issue by bjornharvold** [GoogleCloudPlatform/openjdk-runtime#200]
Hi,

I saw that the openjdk-runtime supports either openjdk8 or openjdk11. I tried setting openjdk11 in my app.yaml. When I deployed I received this error:

`The provided runtime_config.jdk option 'openjdk11' is invalid for JAR deployments. Please use a supported jdk option; ['openjdk8', 'openjdk9'].`

Does this mean I can only use Java 11 when deploying a WAR container?

Thank you
Bjorn

**Comment by pk-op-06** [comment]
Still the same after 3 years 👎🏻

**Comment by bjornharvold** [comment]
For anyone coming across this... switch to Cloud Run today!

**Comment by jinglundong** [comment]
Hi folks, I want to share an update about the OpenJDK 11 and 17 support. We are going to make them public preview in the coming weeks, if not days. 

Please update your app.yaml as follow and use gcloud version >= 420.0.0 to `gcloud app deploy` your GAE Flex application. Any feedback would be appreciated. 

```
runtime: java
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "17"
```

```
runtime: java
env: flex

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "11"
```

+cc, @kappratiksha @jama22

**Comment by BullyWiiPlaza** [comment]
Still, the latest supported version is `openjdk9` 😒

`app.yaml`:

```
runtime: java
env: flex
runtime_config:
  jdk: openjdk9
...
```
I wanted to use `openjdk19`.

**Comment by jinglundong** [comment]
GAE Flex supports Java 8, 11 and 17 now. [Release notes](https://cloud.google.com/appengine/docs/flexible/java/release-notes#April_18_2023).

```
runtime: java
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "17"
```
