### ISSUE TITLE
Network is unreachable.

### ISSUE THREAD

**Issue by nickhristov** [GoogleCloudPlatform/openjdk-runtime#41]
Hello.

Not sure if i should file the issue here or where, however, in my pet project I cannot seem to be able to make networking calls outside of the docker container once deployed to the GAE.

Here is the stack trace:

```
18:32:06.000 2017-01-14 02:32:06.670 [vert.x-eventloop-thread-1] ERROR io.vertx.ext.web.authentication.GoogleUserDataRetriever - Connection error:Network is unreachable: www.googleapis.com/2607:f8b0:4001:c0d:0:0:0:5f:443
18:32:06.000 io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: www.googleapis.com/2607:f8b0:4001:c0d:0:0:0:5f:443
```

My Dockerfile is the following:

```Dockerfile
FROM gcr.io/google_appengine/openjdk8
RUN useradd -ms /bin/bash vertx
RUN mkdir /app
WORKDIR /app
COPY build/distributions/server.zip /app
RUN unzip /app/server.zip
RUN mv /app/server/* /app
RUN rm -rf /app/server
RUN chown -R vertx /app
USER vertx
EXPOSE 8080
ENV APP_HOME=/app
ENTRYPOINT /app/bin/server
```

And my app.yaml is this:

```yaml
runtime: custom
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

# [START env_variables]
env_variables:
  USE_GAE_MEMCACHE: 1
# [END env_variables]
# [END appyaml]
```
